VeritemaMVC_3/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Veritema.Data;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using System.Text;
using System.IO;

namespace VeritemaMVC_3.Controllers
{
    public class FormData
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }

        // at least make sure these are all initialized to empty string.
        public FormData()
        {
            Name = string.Empty;
            Email = string.Empty;
            Telephone = string.Empty;
            Subject = string.Empty;
            Message = string.Empty;
        }
        public override string ToString()
        {
            // Build Message to publish to Contact Us AWS Topic
            StringBuilder sb = new StringBuilder();
            sb.AppendLine(String.Format("Name: {0}", this.Name));
            sb.AppendLine(String.Format("Email: {0}", this.Email));
            sb.AppendLine(String.Format("Telephone: {0}", this.Telephone));
            sb.AppendLine(String.Format("Subject: {0}", this.Subject));
            sb.AppendLine(String.Format("Message: {0}", this.Message));
            return sb.ToString();
        }
    }

    public class ContactController : Controller
    {
        public ContactController()
        {
            var x = 1;
        }

        public ActionResult Index()
        {
            string text = string.Empty;
           // var image = Captcha.Generate(6, 100, 50, out text);
            return View();
        }

        [HttpGet]
        public JsonResult Submit(FormData data)
        {
            List<PublishResponse> publishResponses = new List<PublishResponse>();


            string accessKey = GetConfigValue("AWSAccessKeyId");
            string secretKey = GetConfigValue("AWSSecretKeyValue");
            var client = new AmazonSimpleNotificationServiceClient(accessKey, secretKey, Amazon.RegionEndpoint.USEast1);
            
            var request = new ListTopicsRequest();
            
            // only want the ContactUs Topic Arn
            // for now this is hard-coded - future refactor should place it in web config or database.
            // Looks like IAWSChannelLoader etc got wiped. For now, just run with web.config
            string contactUsARN = GetConfigValue("AWContactUsARN");

            /* Only one ARN, so following proof of concept not needed, commented out
            var listTopicsResponse = client.ListTopics(request);
            foreach (var topic in listTopicsResponse.Topics)
            {
              
            }
            */

            // Basic functionality works. Need to parse the publishResponse collection for specific service messages (failed, success, etc)
            // but for now simply assume if it published it was a success.
            publishResponses.Add(client.Publish(new PublishRequest
            {
                TopicArn = contactUsARN,
                Message = data.ToString()
            }));
            return Json(publishResponses, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Directions()
        {
            return View();
        }

        [HttpGet]
        public System.Web.Mvc.FileResult GetVideo()
        {
            string filePath = Server.MapPath("/images/small_circle_mtn.mp4");

            //   using (FileStream stream = new FileStream(filePath, FileMode.Open))
            //       return File(stream, "video/mp4");
             
            var stream = new MemoryStream();
            using (StreamWriter writer = new StreamWriter(stream))
            {
                // using (CsvWriter csv = new CsvWriter(writer))
                using (FileStream fileStream = new FileStream(filePath, FileMode.Open))
                {
                    stream.Seek(0, SeekOrigin.Begin);
                    return File(stream, "video/mp4");
                }
            }
        }

        /// <summary>
        /// Returns config value, if exists and found, or empty string.
        /// </summary>
        /// <param name="key">web config key</param>
        /// <returns>config value as string</returns>
        private string GetConfigValue(string key)
        {
            return !String.IsNullOrEmpty(System.Configuration.ConfigurationManager.AppSettings[key]) ? System.Configuration.ConfigurationManager.AppSettings[key].ToString() : string.Empty;

        }

    }
}

VeritemaMVC_3/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VeritemaMVC_3.Controllers
{
    public class EventsController : Controller
    {
        // GET: Events
        public ActionResult Index()
        {
            return View();
        }

        // GET: Events/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Events/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Events/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

VeritemaMVC_3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VeritemaMVC_3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Video()
        {
            return View();
        }
            
    }
}

VeritemaMVC_3/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;

namespace ASPNET_Web_Api_SelfHost_VideoStreaming.Controllers
{
    public class VideosController : ApiController
    {
        public HttpResponseMessage Get()
        {
            IEnumerable<string> videos = new List<string>() { "Christmas", "Illumination" };
            HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK, videos);
            return response;
        }
    }
}

VeritemaMVC_3/Views/Home/Index.cshtml
<style>
    .carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        max-width: 100%;
        line-height: 1;
        width: 100%;
        height:100%;
    }

    #panel-sidebar {
        color: #ffffff;
    }

    .italics-box {
        border: 1px dotted;
        color: #777777;
        background-color: #e7e7e7;
        border: #c2c2c2;
        font-style: italic;
        padding: 10px 20px 0px 20px;
        font-size: 12px;
        display: block;
    }

    .remove-all-margin-padding {
        margin: 0 !important;
        padding: 0 !important;
    }

    .maindiv-intro {
        background-color: #3d3d3d;
        background-repeat: repeat-x;
        text-align: center;
        color: #ccc;
    }

      .maindiv-intro > p {
          padding-left: 8px;
          padding-right: 8px;
      }

      #showcase_small {
          margin-bottom: 5px;
      }

  .carousel-control.left, .carousel-control.right {
   background-image:none !important;
   filter:none !important;
}
</style>
<link href="@Url.Content("/css/jplayer.blue.monday.css")" rel="stylesheet" />

<div class="row-fluid">
    <div class="col-md-8">

    </div>
    <div class="col-md-4">
   
    </div>
</div>

<div class="container" id="carousel-contain">
    <div class="row">
            <div id="showcase"  class="hidden-xs">
                <div id="showcase1">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">

                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="/images/mountain_screen.png" border="0" alt="">

                            </div>

                            <div class="item">

                            </div>

                            <div class="item">

                            </div>


                        </div>

                    </div>
                </div>
                <div id="showcase2">
                    <div id="showcase2-1">
                        <div class="moduletable_showcase2">
                            <div class="custom_showcase2">
                                <span style="color: #ffffff; text-align: right">
                                    This Month
                                </span>
                                <br />
                                <span style="color: #ffffff; text-align: right;  font-weight:bold">
                                    ONE WEEK FREE TRIAL<br />
                                </span>
                                <p></p>
                                <span class="pull-right hidden-sm hidden-xs">
                                    <button id="btnLearnMore_lg" class="btn-md btn-primary">Learn More</button>
                                </span>
                                <span class="pull-right hidden-lg hidden-md">
                                    <button id="btnLearnMore_sm" class="btn-sm btn-primary">Learn More</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div id="showcase2-2">
                        <div class="moduletable_showcase2">
                            <div class="custom_showcase2">
                                <span style="color: #ffffff; text-align: right">
                                    Purchase Uniforms
                                </span>
                                <br />
                                <span style="color: #ffffff; text-align: right; font-weight:bold">
                                    GIS AND RASH GUARDS
                                </span>
                                <p></p>
                                <span class="pull-right hidden-sm hidden-xs">
                                    <button id="btnStore_lg" class="btn-sm btn-primary">Visit Our Store</button>
                                </span>
                                <span class="pull-right hidden-lg hidden-md">
                                    <button id="btnStore_sm" class="btn-md btn-primary">Visit Our Store</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div id="showcase2-3">
                        <div class="moduletable_showcase2">
                            <div class="custom_showcase2">
                                <span style="color: #ffffff; text-align: right">
                                    Instructor Classes
                                </span>
                                <br />
                                <span style="color: #ffffff; text-align: right; font-weight:bold">
                                    SEMINARS - Updated 12.21.2017
                                </span>
                                <p></p>
                             
                                <span class="pull-right hidden-sm hidden-xs">
                                    <button id="btnEvents_lg" class="btn-md btn-primary">Events Calendar</button>
                                </span>
                                <span class="pull-right hidden-lg hidden-md">
                                    <button id="btnEvents_sm"  class="btn-sm btn-primary">Events Calendar</button>
                                </span>
                              
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row maindiv-intro">
            <p style="font-size: large;font-weight:bold">SMALL CIRCLE HAPKIDO CREED </p>
            <p></p>
            <p style="font-size: medium">
                To build true self-confidence through knowledge in the mind, honest in the heart, and strength in the body.
            </p>
            <p></p>
            <p style="font-size: medium">
                To develop love and trust with family and friends, show respect to seniors and to form a strong and happy world.
            </p>
            <p></p>
            <p style="font-size: medium">
                Never to fight for selfish goals, but to defend life, justice, and peace.
            </p>
        </div>
    </div> 
<div class="row-fluid">
    <div class="col-md-4 col-lg-4" style="padding-top: 15px; padding-bottom: 15px">
        <span class="badge" style="background-color: #404040"><span class="glyphicon glyphicon-align-left glyphicon-calendar" aria-hidden="true"></span></span>
        <span>Available NOW!</span>
        <p></p>
        <span>Gift certificates for private lessons, classes and equipment are available at $30.00, $60.00 and $90.00 increments.</span>
    </div>
    <div class="col-md-4 col-lg-4" style="padding-top: 15px; padding-bottom: 15px">
        <span class="badge" style="background-color: #404040"><span class="glyphicon glyphicon-align-left glyphicon-thumbs-up"></span></span>
        <span>BIG BROTHER PROGRAM</span>
        <p></p>
        <span>Is your Teen an at risk juvenile? We can help by placing them in a personalized mentor program that teaches honor and respect.</span>
    </div>
    <div class="col-md-4 col-lg-4" style="padding-top: 15px; padding-bottom: 15px">
        <span class="badge" style="background-color: #404040"><span class="glyphicon glyphicon-align-left glyphicon-certificate"></span></span>
        <span>BULLYPROOF YOUR CHILDREN</span>
        <p></p>
        <span>Children from ages 5 to 12 can find their courage in our Little Dragons program. This class allows kids to embrace martial arts and helps build life skills.</span>
    </div>
    <div class="col-md-12 italics-box">
        <p style="text-align: center;" align="center"><strong><span style="font-family: 'Arial Black','sans-serif';">FITNESS KICKBOXING - MUAY THAI - BRAZILIAN JIU-JITSU - HAPKIDO - CONDITIONING - TAI CHI CHAUN - JUDO</span></strong></p>

    </div>
    <div class="row-fluid">
        <div class="col-md-3" style="padding-top: 20px; padding-bottom: 15px">
            <p style="font-size:large">Save 50% Today</p>
            Whether you are trying to get in shape or stay in shape. We have it all for the whole family, and the martial arts training you will receive is second to none, call us today and save 50% off on your first month.
        </div>
        <div class="col-md-3" style="padding-top: 20px; padding-bottom: 15px">
            <img src="/images/gallerymodule/bjj_front.jpg" border="0" alt="">
        </div>
        <div class="col-md-3" style="padding-top: 20px; padding-bottom: 15px">
            <img src="/images/gallerymodule/muay-thai_front.jpg" border="0" alt="">
        </div>
        <div class="col-md-3" style="padding-top: 20px; padding-bottom: 15px">
            <img src="/images/gallerymodule/Judo_front.jpg" border="0" alt="">
        </div>
    </div>
    <!--
    <div id="bottom" class="row-fluid">
        <div class="col-md-4 col-lg-4" style="padding-top: 15px; padding-bottom: 15px">
            <span class="title1">
                <span class="badge" style="background-color: #404040"><span class="glyphicon glyphicon-time" aria-hidden="true"></span></span>
                HOME TRAINING AVAILABLE
            </span>
        </div>

        <div class="col-md-4 col-lg-4" style="padding-top: 15px; padding-bottom: 15px">
            <span class="title1">
                OPEN 10 SERVICE OPTIONS
            </span>
        </div>

        <div class="col-md-4 col-lg-4" style="padding-top: 15px; padding-bottom: 15px">
            <span class="title1">
                <span class="badge" style="background-color: #404040"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span></span>
                FREE PT WITH MEMBERSHIP
            </span>
        </div>
    </div>
        -->
</div>


<script type="text/javascript">
    //<![CDATA[
    

    $(document).ready(function () {

      
        $('#jquery_jplayer_1').jPlayer({
            swfPath: '../dist/jplayer',
            solution: 'html, flash',
            supplied: 'webmv, ogv, m4v',
            preload: 'metadata',
            volume: 0.8,
            muted: false,
            backgroundColor: '#000000',
            cssSelectorAncestor: '#jp_container_1',
            cssSelector: {
                videoPlay: '.jp-video-play',
                play: '.jp-play',
                pause: '.jp-pause',
                stop: '.jp-stop',
                seekBar: '.jp-seek-bar',
                playBar: '.jp-play-bar',
                mute: '.jp-mute',
                unmute: '.jp-unmute',
                volumeBar: '.jp-volume-bar',
                volumeBarValue: '.jp-volume-bar-value',
                volumeMax: '.jp-volume-max',
                playbackRateBar: '.jp-playback-rate-bar',
                playbackRateBarValue: '.jp-playback-rate-bar-value',
                currentTime: '.jp-current-time',
                duration: '.jp-duration',
                title: '.jp-title',
                fullScreen: '.jp-full-screen',
                restoreScreen: '.jp-restore-screen',
                repeat: '.jp-repeat',
                repeatOff: '.jp-repeat-off',
                gui: '.jp-gui',
                noSolution: '.jp-no-solution'
            },
            errorAlerts: false,
            warningAlerts: false
        });


    });
//]]>
</script>





<script>
    $(document).ready(function () {
        // clear it out with pure javascript - quicker
        $("#headerBreadCrumbs").text('');
        $("#headerBreadCrumbs").append("<li><a href='#'>Home</a></li>");
    });


    $('#btnLearnMore_lg').click(function () {
        var url = '@Url.Action("Index", "Contact", new { })';
        window.location.href = url;
    });
    $('#btnLearnMore_sm').click(function () {
        var url = '@Url.Action("Index", "Contact", new { })';
        window.location.href = url;
    });

    $('#btnStore_sm').click(function () {
        window.open('https://squareup.com/market/small-circle-hapkido');
    });
    $('#btnStore_lg').click(function () {
        window.open('https://squareup.com/market/small-circle-hapkido');
    });

    $('#btnEvents_sm').click(function () {
        var url = '@Url.Action("Index", "Events", new { })';
        window.location.href = url;
    });
    $('#btnEvents_lg').click(function () {
        var url = '@Url.Action("Index", "Events", new { })';
        window.location.href = url;
    });


</script>

VeritemaMVC_3/Views/Home/Video.cshtml
@{
    ViewBag.Title = "Video";
}
<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
    <div class="jp-type-playlist">
        <div class="jp-gui jp-interface">
            <div class="jp-controls">
                <button class="jp-previous" role="button" tabindex="0">previous</button>
                <button class="jp-play" role="button" tabindex="0">play</button>
                <button class="jp-next" role="button" tabindex="0">next</button>
                <button class="jp-stop" role="button" tabindex="0">stop</button>
            </div>
            <div class="jp-progress">
                <div class="jp-seek-bar">
                    <div class="jp-play-bar"></div>
                </div>
            </div>
            <div class="jp-volume-controls">
                <button class="jp-mute" role="button" tabindex="0">mute</button>
                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>
            </div>
            <div class="jp-time-holder">
                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
            </div>
            <div class="jp-toggles">
                <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
            </div>
        </div>
        <div class="jp-playlist">
            <ul>
                <li>&nbsp;</li>
            </ul>
        </div>
        <div class="jp-no-solution">
            <span>Update Required</span>
            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
        </div>
    </div>
</div>
<!--
    mp4: "@Url.RouteUrl("DefaultApi", new { httproute = "", controller = "camera", id = "fromvideo", videoName = "small_circle_mtn" })"    

<script>
$(document).ready(function(){
  $("#jquery_jplayer_1").jPlayer({
   ready: function () {
    $(this).jPlayer("setMedia", {
        mp4: "http://www.veritema.com/api/camera/fromvideo?videoName=small_circle_mtn"
    });
   },
   swfPath: "~/js",
   supplied: "m4v"
  });
 });
</script>
    -->